### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by Kit-p** [Kit-p/json-kit#4]
### Current Stage
Released - Feature Complete

### Tasks
- [x] Initialize the project (#3)
- [x] Setup unit tests (#3)
- [x] Setup CI/CD (#15) (#16) (#18) (#19) (#20) (#21) (#26) (#27) (#29)
- [x] Setup automatic dependency updates (#37) (#39)
- [x] Setup documentations (#45)
- [x] Implement JSON conversion from/to string (#6) (#13)
- [x] Implement Extended JSON conversion from/to string (#6) (#13)
- [x] Implement conversion between JSON and Extended JSON (#42)
- [x] Implement JSON minification and restoration (#6) (#13)
- [x] Implement Extended JSON minification and restoration (#6) (#13)
- [x] Implement JSON compression and decompression (#7) (#13)
- [x] Implement Extended JSON compression and decompression (#7) (#13)
---

Thank you for visiting here, feel free to star this repository to support my development!
